# Generated by Django 4.2.1 on 2023-06-01 15:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orders', models.CharField(blank=True, max_length=50, verbose_name='Мои заказы')),
                ('wishlist', models.CharField(blank=True, max_length=50, verbose_name='Cписок желаний')),
                ('browseed_items', models.CharField(blank=True, max_length=50, verbose_name='Просмотренные товары')),
                ('newsletters', models.CharField(blank=True, max_length=50, verbose_name='Рассылки')),
                ('my_wallet', models.CharField(blank=True, max_length=50, verbose_name='Мой кошелек')),
                ('my_reviews', models.CharField(blank=True, max_length=50, verbose_name='Мои отзывы')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Профиль пользователя',
                'verbose_name_plural': 'Профили пользователей',
            },
        ),
    ]
