# Generated by Django 4.1.3 on 2023-05-06 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BrandElectronics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('image', models.ImageField(upload_to='brand_Electronics_images/')),
            ],
            options={
                'verbose_name': 'Марка электроники',
                'verbose_name_plural': 'Марки электроники',
            },
        ),
        migrations.CreateModel(
            name='BrandHouseholdAppliances',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('image', models.ImageField(upload_to='brand_HouseholdAppliances_images/')),
            ],
            options={
                'verbose_name': 'Марка бытовой техники холодильники',
                'verbose_name_plural': 'Марки бытовой техники холодильники',
            },
        ),
        migrations.CreateModel(
            name='BrandWashingMachine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('image', models.ImageField(upload_to='brand_WashingMachine_images/')),
            ],
            options={
                'verbose_name': 'Марка стиральные машинки',
                'verbose_name_plural': 'Марки стиральные машинки',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('image', models.ImageField(upload_to='category_photo/', verbose_name='Иконки')),
                ('url', models.SlugField(max_length=200, unique=True)),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ElectronicsDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Название')),
                ('series', models.CharField(max_length=100, verbose_name='Серия')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('display_size', models.CharField(max_length=50, verbose_name='Размер дисплея')),
                ('main_camera', models.CharField(blank=True, max_length=100, null=True, verbose_name='Основная камера')),
                ('battery_capacity', models.CharField(max_length=50, verbose_name='Ёмкость батареи')),
                ('CPU', models.CharField(max_length=50, verbose_name='Процессор')),
                ('ram', models.CharField(max_length=50, verbose_name='Оперативная память')),
                ('operating_system', models.CharField(max_length=50, verbose_name='Операционная система')),
                ('screen_refresh_rate', models.CharField(blank=True, max_length=30, null=True, verbose_name='Частота обновления экрана')),
                ('ram_type', models.CharField(blank=True, max_length=20, null=True, verbose_name='Тип оперативной памяти')),
                ('ssd_capacity', models.CharField(blank=True, max_length=20, null=True, verbose_name='Объём SSD')),
                ('image', models.ImageField(upload_to='MobileTvTabletDevice/', verbose_name='Фото')),
                ('url', models.SlugField(default='', max_length=200, unique=True)),
                ('draft', models.BooleanField(default=False, verbose_name='Черновик')),
                ('by_action', models.BooleanField(default=False, verbose_name='Акциооный товар')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.brandelectronics', verbose_name='Марка')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Электроника',
                'verbose_name_plural': 'Электроника',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Hfridge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Название')),
                ('series', models.CharField(max_length=100, verbose_name='Серия')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('fridge_capacity', models.PositiveSmallIntegerField(verbose_name='Объем холодильной камеры, л')),
                ('weight', models.PositiveSmallIntegerField(verbose_name='Вес, кг')),
                ('color', models.CharField(max_length=50, verbose_name='Цвет')),
                ('image', models.ImageField(upload_to='hfridge/', verbose_name='Изображение')),
                ('url', models.SlugField(default='', max_length=200, unique=True)),
                ('draft', models.BooleanField(default=False, verbose_name='Черновик')),
                ('by_action', models.BooleanField(default=False, verbose_name='Акциооный товар')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.brandhouseholdappliances', verbose_name='Марка')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Холодильник',
                'verbose_name_plural': 'Холодильники',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RatingsStar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.PositiveSmallIntegerField(default=0, verbose_name='Значение')),
            ],
            options={
                'verbose_name': 'Звезда рейтинга',
                'verbose_name_plural': 'Звезды рейтинга',
                'ordering': ['-value'],
            },
        ),
        migrations.CreateModel(
            name='Salesman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('image', models.ImageField(upload_to='salesman/', verbose_name='Иконка')),
            ],
            options={
                'verbose_name': 'Продавец',
                'verbose_name_plural': 'Продавцы',
            },
        ),
        migrations.CreateModel(
            name='WashingMachine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Название')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('maximum_laundry_load', models.CharField(max_length=50, verbose_name='Загрузка')),
                ('color', models.CharField(max_length=20, verbose_name='Цвет')),
                ('weight', models.PositiveSmallIntegerField(verbose_name='Вес, кг')),
                ('spin_speed', models.CharField(max_length=50, verbose_name='Скорость отжима')),
                ('image', models.ImageField(upload_to='washing_machines/', verbose_name='Фото')),
                ('url', models.SlugField(default='', max_length=200, unique=True)),
                ('draft', models.BooleanField(default=False, verbose_name='Черновик')),
                ('by_action', models.BooleanField(default=False, verbose_name='Акциооный товар')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.brandhouseholdappliances', verbose_name='Марка')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Стиральная машина',
                'verbose_name_plural': 'Стиральные машинки',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('text', models.TextField(max_length=5000, verbose_name='Коментарий')),
                ('email', models.EmailField(max_length=254)),
                ('electronicsDevice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.electronicsdevice', verbose_name='Товар электоники')),
                ('hfridgeDevice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.hfridge', verbose_name='Товар холодильники')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.review', verbose_name='Родитель')),
                ('washingDevice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.washingmachine', verbose_name='Товар стиральные машинки')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=60, verbose_name='IP адресс')),
                ('electronicsDevice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.electronicsdevice', verbose_name='Товар электоники')),
                ('hfridgeDevice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.hfridge', verbose_name='Товар холодильники')),
                ('star', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.ratingsstar', verbose_name='Звезда')),
                ('washingDevice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.washingmachine', verbose_name='Товар стиральные машинки')),
            ],
            options={
                'verbose_name': 'Рейтинг',
                'verbose_name_plural': 'Рейтинги',
            },
        ),
    ]
