# Generated by Django 4.1.3 on 2023-05-08 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BrandWashingMachine',
        ),
        migrations.AlterModelOptions(
            name='brandhouseholdappliances',
            options={'verbose_name': 'Марка бытовой техники', 'verbose_name_plural': 'Марки бытовой техники'},
        ),
    ]
