# Generated by Django 4.1.3 on 2023-05-03 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='electronicsdevice',
            name='url',
            field=models.SlugField(default='NULL', max_length=200, unique=True),
        ),
        migrations.AddField(
            model_name='hfridge',
            name='url',
            field=models.SlugField(default='NULL', max_length=200, unique=True),
        ),
        migrations.AddField(
            model_name='washingmachine',
            name='url',
            field=models.SlugField(default='NULL', max_length=200, unique=True),
        ),
    ]
