# Generated by Django 4.1.3 on 2023-05-05 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='electronicsdevice',
            name='by_action',
            field=models.BooleanField(default=False, verbose_name='Акциооный товар'),
        ),
        migrations.AddField(
            model_name='hfridge',
            name='by_action',
            field=models.BooleanField(default=False, verbose_name='Акциооный товар'),
        ),
        migrations.AddField(
            model_name='washingmachine',
            name='by_action',
            field=models.BooleanField(default=False, verbose_name='Акциооный товар'),
        ),
    ]
