# Generated by Django 4.1.3 on 2023-05-03 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_electronicsdevice_url_hfridge_url_washingmachine_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brandelectronics',
            options={'verbose_name': 'Марка электроники', 'verbose_name_plural': 'Марки электроники'},
        ),
        migrations.AlterModelOptions(
            name='brandhouseholdappliances',
            options={'verbose_name': 'Марка бытовой техники холодильники', 'verbose_name_plural': 'Марки бытовой техники холодильники'},
        ),
        migrations.AlterModelOptions(
            name='brandwashingmachine',
            options={'verbose_name': 'Марка стиральные машинки', 'verbose_name_plural': 'Марки стиральные машинки'},
        ),
        migrations.AlterField(
            model_name='electronicsdevice',
            name='url',
            field=models.SlugField(default='', max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='hfridge',
            name='url',
            field=models.SlugField(default='', max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='washingmachine',
            name='url',
            field=models.SlugField(default='', max_length=200, unique=True),
        ),
    ]
