# Generated by Django 4.2.1 on 2023-05-27 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_category_name_en_category_name_ru'),
    ]

    operations = [
        migrations.AddField(
            model_name='brandproduct',
            name='title_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='brandproduct',
            name='title_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_en',
            field=models.CharField(max_length=300, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_ru',
            field=models.CharField(max_length=300, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='review',
            name='name_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='review',
            name='name_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='review',
            name='text_en',
            field=models.TextField(max_length=5000, null=True, verbose_name='Коментарий'),
        ),
        migrations.AddField(
            model_name='review',
            name='text_ru',
            field=models.TextField(max_length=5000, null=True, verbose_name='Коментарий'),
        ),
        migrations.AddField(
            model_name='salesman',
            name='name_en',
            field=models.CharField(max_length=50, null=True, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='salesman',
            name='name_ru',
            field=models.CharField(max_length=50, null=True, verbose_name='Имя'),
        ),
    ]
