# Generated by Django 4.2.1 on 2023-05-18 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_product_cpu_alter_product_battery_capacity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='salesman',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.salesman', verbose_name='Продавец'),
        ),
        migrations.AlterField(
            model_name='product',
            name='url',
            field=models.SlugField(max_length=200, unique=True),
        ),
    ]
