# Generated by Django 4.2.1 on 2023-05-27 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_brandproduct_title_en_brandproduct_title_ru_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='display_size_en',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Размер дисплея'),
        ),
        migrations.AddField(
            model_name='product',
            name='display_size_ru',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Размер дисплея'),
        ),
    ]
