# Generated by Django 4.2.1 on 2023-05-29 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_product_display_size_en_product_display_size_ru'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='review',
            name='name_ru',
        ),
        migrations.RemoveField(
            model_name='review',
            name='text_en',
        ),
        migrations.RemoveField(
            model_name='review',
            name='text_ru',
        ),
        migrations.AddField(
            model_name='brandproduct',
            name='title_ua',
            field=models.CharField(max_length=100, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_ua',
            field=models.CharField(max_length=200, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='product',
            name='CPU_en',
            field=models.CharField(blank=True, max_length=122, null=True, verbose_name='Процессор'),
        ),
        migrations.AddField(
            model_name='product',
            name='CPU_ru',
            field=models.CharField(blank=True, max_length=122, null=True, verbose_name='Процессор'),
        ),
        migrations.AddField(
            model_name='product',
            name='CPU_ua',
            field=models.CharField(blank=True, max_length=122, null=True, verbose_name='Процессор'),
        ),
        migrations.AddField(
            model_name='product',
            name='battery_capacity_en',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Ёмкость батареи'),
        ),
        migrations.AddField(
            model_name='product',
            name='battery_capacity_ru',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Ёмкость батареи'),
        ),
        migrations.AddField(
            model_name='product',
            name='battery_capacity_ua',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Ёмкость батареи'),
        ),
        migrations.AddField(
            model_name='product',
            name='code_en',
            field=models.IntegerField(blank=True, null=True, verbose_name='Код товара'),
        ),
        migrations.AddField(
            model_name='product',
            name='code_ru',
            field=models.IntegerField(blank=True, null=True, verbose_name='Код товара'),
        ),
        migrations.AddField(
            model_name='product',
            name='code_ua',
            field=models.IntegerField(blank=True, null=True, verbose_name='Код товара'),
        ),
        migrations.AddField(
            model_name='product',
            name='color_en',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Цвет'),
        ),
        migrations.AddField(
            model_name='product',
            name='color_ru',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Цвет'),
        ),
        migrations.AddField(
            model_name='product',
            name='color_ua',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Цвет'),
        ),
        migrations.AddField(
            model_name='product',
            name='display_size_ua',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Размер дисплея'),
        ),
        migrations.AddField(
            model_name='product',
            name='fridge_capacity_en',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Объем холодильной камеры, л'),
        ),
        migrations.AddField(
            model_name='product',
            name='fridge_capacity_ru',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Объем холодильной камеры, л'),
        ),
        migrations.AddField(
            model_name='product',
            name='fridge_capacity_ua',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Объем холодильной камеры, л'),
        ),
        migrations.AddField(
            model_name='product',
            name='main_camera_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Основная камера'),
        ),
        migrations.AddField(
            model_name='product',
            name='main_camera_ru',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Основная камера'),
        ),
        migrations.AddField(
            model_name='product',
            name='main_camera_ua',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Основная камера'),
        ),
        migrations.AddField(
            model_name='product',
            name='maximum_laundry_load_en',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Загрузка'),
        ),
        migrations.AddField(
            model_name='product',
            name='maximum_laundry_load_ru',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Загрузка'),
        ),
        migrations.AddField(
            model_name='product',
            name='maximum_laundry_load_ua',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Загрузка'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_ua',
            field=models.CharField(max_length=300, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='product',
            name='operating_system_en',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Операционная система'),
        ),
        migrations.AddField(
            model_name='product',
            name='operating_system_ru',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Операционная система'),
        ),
        migrations.AddField(
            model_name='product',
            name='operating_system_ua',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Операционная система'),
        ),
        migrations.AddField(
            model_name='product',
            name='price_en',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Цена'),
        ),
        migrations.AddField(
            model_name='product',
            name='price_ru',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Цена'),
        ),
        migrations.AddField(
            model_name='product',
            name='price_ua',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Цена'),
        ),
        migrations.AddField(
            model_name='product',
            name='ram_en',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Оперативная память'),
        ),
        migrations.AddField(
            model_name='product',
            name='ram_ru',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Оперативная память'),
        ),
        migrations.AddField(
            model_name='product',
            name='ram_type_en',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Тип оперативной памяти'),
        ),
        migrations.AddField(
            model_name='product',
            name='ram_type_ru',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Тип оперативной памяти'),
        ),
        migrations.AddField(
            model_name='product',
            name='ram_type_ua',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Тип оперативной памяти'),
        ),
        migrations.AddField(
            model_name='product',
            name='ram_ua',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Оперативная память'),
        ),
        migrations.AddField(
            model_name='product',
            name='screen_refresh_rate_en',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Частота обновления экрана'),
        ),
        migrations.AddField(
            model_name='product',
            name='screen_refresh_rate_ru',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Частота обновления экрана'),
        ),
        migrations.AddField(
            model_name='product',
            name='screen_refresh_rate_ua',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Частота обновления экрана'),
        ),
        migrations.AddField(
            model_name='product',
            name='series_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Серия'),
        ),
        migrations.AddField(
            model_name='product',
            name='series_ru',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Серия'),
        ),
        migrations.AddField(
            model_name='product',
            name='series_ua',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Серия'),
        ),
        migrations.AddField(
            model_name='product',
            name='spin_speed_en',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Скорость отжима'),
        ),
        migrations.AddField(
            model_name='product',
            name='spin_speed_ru',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Скорость отжима'),
        ),
        migrations.AddField(
            model_name='product',
            name='spin_speed_ua',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Скорость отжима'),
        ),
        migrations.AddField(
            model_name='product',
            name='ssd_capacity_en',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Объём SSD'),
        ),
        migrations.AddField(
            model_name='product',
            name='ssd_capacity_ru',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Объём SSD'),
        ),
        migrations.AddField(
            model_name='product',
            name='ssd_capacity_ua',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Объём SSD'),
        ),
        migrations.AddField(
            model_name='product',
            name='weight_en',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Вес, кг'),
        ),
        migrations.AddField(
            model_name='product',
            name='weight_ru',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Вес, кг'),
        ),
        migrations.AddField(
            model_name='product',
            name='weight_ua',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Вес, кг'),
        ),
        migrations.AddField(
            model_name='salesman',
            name='name_ua',
            field=models.CharField(max_length=50, null=True, verbose_name='Имя'),
        ),
    ]
