# Generated by Django 4.2.1 on 2023-06-01 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_review_name_en_remove_review_name_ru_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brandproduct',
            name='title_ua',
        ),
        migrations.RemoveField(
            model_name='category',
            name='name_ua',
        ),
        migrations.RemoveField(
            model_name='product',
            name='CPU_ua',
        ),
        migrations.RemoveField(
            model_name='product',
            name='battery_capacity_ua',
        ),
        migrations.RemoveField(
            model_name='product',
            name='code_ua',
        ),
        migrations.RemoveField(
            model_name='product',
            name='color_ua',
        ),
        migrations.RemoveField(
            model_name='product',
            name='display_size_ua',
        ),
        migrations.RemoveField(
            model_name='product',
            name='fridge_capacity_ua',
        ),
        migrations.RemoveField(
            model_name='product',
            name='main_camera_ua',
        ),
        migrations.RemoveField(
            model_name='product',
            name='maximum_laundry_load_ua',
        ),
        migrations.RemoveField(
            model_name='product',
            name='name_ua',
        ),
        migrations.RemoveField(
            model_name='product',
            name='operating_system_ua',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price_ua',
        ),
        migrations.RemoveField(
            model_name='product',
            name='ram_type_ua',
        ),
        migrations.RemoveField(
            model_name='product',
            name='ram_ua',
        ),
        migrations.RemoveField(
            model_name='product',
            name='screen_refresh_rate_ua',
        ),
        migrations.RemoveField(
            model_name='product',
            name='series_ua',
        ),
        migrations.RemoveField(
            model_name='product',
            name='spin_speed_ua',
        ),
        migrations.RemoveField(
            model_name='product',
            name='ssd_capacity_ua',
        ),
        migrations.RemoveField(
            model_name='product',
            name='weight_ua',
        ),
        migrations.RemoveField(
            model_name='salesman',
            name='name_ua',
        ),
    ]
