# Generated by Django 4.2.1 on 2023-06-04 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_brandproduct_title_ua_remove_category_name_ua_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='battery_capacity_en',
        ),
        migrations.RemoveField(
            model_name='product',
            name='battery_capacity_ru',
        ),
        migrations.RemoveField(
            model_name='product',
            name='code_en',
        ),
        migrations.RemoveField(
            model_name='product',
            name='code_ru',
        ),
        migrations.RemoveField(
            model_name='product',
            name='display_size_en',
        ),
        migrations.RemoveField(
            model_name='product',
            name='display_size_ru',
        ),
        migrations.RemoveField(
            model_name='product',
            name='fridge_capacity_en',
        ),
        migrations.RemoveField(
            model_name='product',
            name='fridge_capacity_ru',
        ),
        migrations.RemoveField(
            model_name='product',
            name='maximum_laundry_load_en',
        ),
        migrations.RemoveField(
            model_name='product',
            name='maximum_laundry_load_ru',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price_en',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price_ru',
        ),
        migrations.RemoveField(
            model_name='product',
            name='series_en',
        ),
        migrations.RemoveField(
            model_name='product',
            name='series_ru',
        ),
        migrations.RemoveField(
            model_name='product',
            name='spin_speed_en',
        ),
        migrations.RemoveField(
            model_name='product',
            name='spin_speed_ru',
        ),
        migrations.RemoveField(
            model_name='product',
            name='weight_en',
        ),
        migrations.RemoveField(
            model_name='product',
            name='weight_ru',
        ),
    ]
