version: '3'

services:
  web:
    build: .
    restart: always
    depends_on:
      - mysql
      - redis
    ports:
      - "8000:8000"

  mysql:
    image: mysql:8
    restart: always
    environment:
      MYSQL_DATABASE: Create_MySQL_1
      MYSQL_ROOT_PASSWORD: 1080Zxc
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "curl", "-f", "-k", "http://localhost:3306"]
      interval: 30s
      timeout: 10s
      retries: 5

  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"